import Layout from "@/components/Layout"
export const metadata = {
  title: 'Mobilebill',
  description: 'Generated by create next app',
}

export default function MobilebillLayout({ children }) {
  return <Layout>{children} </Layout> 
}

