import Layout from "@/components/Layout"
export const metadata = {
  title: 'Gender',
  description: 'Generated by create next app',
}

export default function GenderLayout({ children }) {

  return <>{children} </> 
}

